server:
  port: 8973

spring:
  application:
    name: ribbon-consumer
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

feign:
  client:
    config:
      default:
       connectTimeout: 2000
       readTimeout: 2000
  hystrix:
    enabled: true
    
#myheart.ribbon.NFLoadBalancerRuleClassName=com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
        timeout:
          enabled: true
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
env: dev2019
